-- MySQL Script generated by MySQL Workbench
-- Fri Jan  7 12:48:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema interview_project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `interview_project` ;

-- -----------------------------------------------------
-- Schema interview_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `interview_project` DEFAULT CHARACTER SET utf8 ;
USE `interview_project` ;

-- -----------------------------------------------------
-- Table `interview_project`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `interview_project`.`users` ;

CREATE TABLE IF NOT EXISTS `interview_project`.`users` (
                                                           `id` INT NOT NULL AUTO_INCREMENT,
                                                           `role` VARCHAR(45) NOT NULL,
                                                           `first_name` VARCHAR(45) NULL,
                                                           `last_name` VARCHAR(45) NULL,
                                                           `phone` VARCHAR(45) NULL,
                                                           `email` VARCHAR(45) NOT NULL,
                                                           `password` VARCHAR(45) NOT NULL,
                                                           `years_of_experience` INT NULL,
                                                           `position` VARCHAR(45) NULL,
                                                           PRIMARY KEY (`id`),
                                                           UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interview_project`.`vacancies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `interview_project`.`vacancies` ;

CREATE TABLE IF NOT EXISTS `interview_project`.`vacancies` (
                                                               `id` INT NOT NULL AUTO_INCREMENT,
                                                               `name` VARCHAR(45) NOT NULL,
                                                               `position` VARCHAR(45) NOT NULL,
                                                               `salary` VARCHAR(45) NULL,
                                                               `company_name` VARCHAR(45) NOT NULL,
                                                               PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interview_project`.`interviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `interview_project`.`interviews` ;

CREATE TABLE IF NOT EXISTS `interview_project`.`interviews` (
                                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                                `status` VARCHAR(45) NOT NULL,
                                                                `date` DATE NOT NULL,
                                                                `user_id` INT NOT NULL,
                                                                `vacancy_id` INT NOT NULL,
                                                                PRIMARY KEY (`id`),
                                                                INDEX `fk_interviews_users_idx` (`user_id` ASC) VISIBLE,
                                                                INDEX `fk_interviews_vacancies_idx` (`vacancy_id` ASC) VISIBLE,
                                                                CONSTRAINT `fk_interviews_users`
                                                                    FOREIGN KEY (`user_id`)
                                                                        REFERENCES `interview_project`.`users` (`id`)
                                                                        ON DELETE NO ACTION
                                                                        ON UPDATE NO ACTION,
                                                                CONSTRAINT `fk_interviews_vacancies`
                                                                    FOREIGN KEY (`vacancy_id`)
                                                                        REFERENCES `interview_project`.`vacancies` (`id`)
                                                                        ON DELETE NO ACTION
                                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
